# Generated by Django 5.1 on 2024-08-17 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0002_apilogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='apilogin',
        ),
    ]
