# Generated by Django 5.1 on 2024-08-24 06:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherstack', '0004_api_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_request',
            name='data_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
