# Generated by Django 5.1 on 2024-08-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apilogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'apilogin',
                'managed': False,
            },
        ),
    ]
