# Generated by Django 5.1 on 2024-08-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherstack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='api_request',
            fields=[
                ('city', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=20)),
                ('unit', models.CharField(max_length=10)),
                ('data_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'api_request',
                'managed': False,
            },
        ),
    ]
