# Generated by Django 5.1 on 2024-08-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherstack', '0002_api_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='api_current',
            fields=[
                ('current_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('observation_time', models.CharField(max_length=20)),
                ('temperature', models.IntegerField()),
                ('weather_code', models.IntegerField()),
                ('weather_icons', models.CharField(max_length=255)),
                ('weather_descriptions', models.CharField(max_length=100)),
                ('wind_speed', models.IntegerField()),
                ('wind_degree', models.IntegerField()),
                ('wind_dir', models.CharField(max_length=50)),
                ('pressure', models.IntegerField()),
                ('precip', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('cloudcover', models.IntegerField()),
                ('feelslike', models.IntegerField()),
                ('uv_index', models.IntegerField()),
                ('visibility', models.IntegerField()),
                ('is_day', models.CharField(max_length=10)),
                ('data_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'api_current',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='api_location',
            fields=[
                ('location_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('lat', models.CharField(max_length=20)),
                ('lon', models.CharField(max_length=20)),
                ('timezone_id', models.CharField(max_length=50)),
                ('local_time', models.DateTimeField()),
                ('localtime_epoch', models.CharField(max_length=50)),
                ('utc_offset', models.CharField(max_length=10)),
                ('data_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'api_location',
                'managed': False,
            },
        ),
    ]
