# Generated by Django 5.1 on 2024-08-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherstack', '0003_apilogins'),
    ]

    operations = [
        migrations.CreateModel(
            name='api_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('query', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=20)),
                ('unit', models.CharField(max_length=10)),
            ],
        ),
    ]
