# Generated by Django 5.1 on 2024-08-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherstack', '0005_api_request_data_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_request',
            name='data_date',
            field=models.DateTimeField(),
        ),
    ]
